### ISSUE TITLE
Update FullCalendar and Scheduler

### ISSUE THREAD

**Issue by miguelascifo** [alonoslav/fullcalendar-react#10]
Can you update Fullcalendar and scheduler to make use of their respective latest versions?
Thank you.

**Comment by vadym-vorobel** [comment]
Hi @miguelascifo!

I try to do this in a few days. Hope, nothing was changed in Fullcalendar api

**Comment by vadym-vorobel** [comment]
@miguelascifo 
I've updated fullcalendar version. May you test it in your project? If you'll find any issue, please tell me.

Thanks

**Comment by miguelascifo** [comment]
Many thanks for the fast update. I´ll test it and tell you if I find something wrong.

**Comment by vadym-vorobel** [comment]
@miguelascifo thanks!

Close for now
