### ISSUE TITLE
Cannot read property 'clone' of null

### ISSUE THREAD

**Issue by supun19** [alonoslav/fullcalendar-react#12]
I change state from
this.state = {
            events: [
                {
                    title: 'Default event',
                    start: new Date(),
                    // plus 30 minutes
                    end: new Date(Date.now + 30 * 60 * 1000),
                }
            ],

            date: new Date(),
        };

to
this.setState({ events: [
            {
                title: 'Default event',
                start: new Date(Date.now + 30 * 60 * 1000),
                // plus 30 minutes
                end: new Date(Date.now + 30 * 60 * 2000),
            }
        ]  });
        this.setState({ date: new Date(Date.now + 30 * 60 * 1000)  });

it show error Cannot read property 'clone' of null

**Comment by vadym-vorobel** [comment]
Hello @supun19 
Thanks for your question.

I don't fully understand how exactly you've changed the example code. May I take a look at your modified code?

**Comment by vadym-vorobel** [comment]
Ok, @supun19 

It seems like I've reproduced your problem. Just added this code to the example:

```js
componentDidMount() {
  this.setState({ date: new Date(Date.now + 30 * 60 * 1000) });
}
```

Am I done it right? If so, please tell me, why do you need to modify the state in this way? What the use case you want to solve?

**Comment by vadym-vorobel** [comment]
Close as there is no response from the issuer
