### ISSUE TITLE
How to change the lang?

### ISSUE THREAD

**Issue by v3yr0n** [alonoslav/fullcalendar-react#13]
How can I change the language?
Thanks!

**Comment by vadym-vorobel** [comment]
Hi @v3yr0n 
Did you try to pass localization properties? https://fullcalendar.io/docs/localization

**Comment by v3yr0n** [comment]
yes, but my problem is to import the locale file from the dist/locale folder. How can I do it? 
I've tried import 'meteor/jss:fullcalendar-react/fullcalendar/dist/locale/es.js', import 'meteor/jss:fullcalendar-react/fullcalendar/locale/es.js' and import 'meteor/jss:fullcalendar-react/locale/es.js'

thanks!

**Comment by vadym-vorobel** [comment]
@v3yr0n not sure this is possible from this package. You can't get access to the fullcalendar dist files through the package. You may install it separately and import localization files from it
