### ISSUE TITLE
How to remove default styling

### ISSUE THREAD

**Issue by DeanKamali** [alonoslav/fullcalendar-react#3]
Hello 
how can I go about removing default styling that comes with the package? 

I have noticed that after installing this package, it overwrites my fullcalendar css style, it there is a way to prevent that?

**Comment by vadym-vorobel** [comment]
@DeanKamali hello

The package has no files with styles. It should be `fullcalendar` package styles. Can you provide a screenshot or details of your issue?

**Comment by vadym-vorobel** [comment]
@DeanKamali seems it resolved?
