### ISSUE TITLE
Do not update events after rerender.

### ISSUE THREAD

**Issue by drakeBear** [alonoslav/fullcalendar-react#4]
Hello. I store events in a state and change them to assume when selecting. The function updates the state and adds one more event, but it does not render added event. How can i render new events? Following the example of the documentation, nothing could be understood. Thank you!

**Comment by drakeBear** [comment]
A new array of events I define in options in render functions.
```jsx
    onEventSelect(start, end) {
        let events = this.state.events
        events.push({
            title: 'DefaultSUKA',
            constraint: 'availableForWrite',
            start: start.format(),
            end: end.format()
        })

        this.setState({
            events: events
        })
    }

    render() {
        let { events } = this.state

        let calendarOptions = {
            header: {
                left: '',
                center: '', 
                right: ''
            },
            select: this.onEventSelect,
            ...
            events: events,
        }



        return(
            <div className="row">
                <div className='calendar'>
                    <FullCalendar
                        options={calendarOptions} />
                </div>
            </div>
        )
    }

**Comment by vadym-vorobel** [comment]
@drakeBear thanks for your question.

I've added an example solution for your problem. You can look on it [here](https://github.com/alonoslav/fullcalendar-react/blob/master/examples/simple/client/main.js#L63).

The main idea to use function as a source of events. Than, your events will be reactive.

**Comment by drakeBear** [comment]
Thank you so much.

**Comment by drakeBear** [comment]
And another question.
Its will be working after i exclude sheduler from this. It isn't exactly free additional to full-calendar and so isn't approach for my project.

**Comment by vadym-vorobel** [comment]
@drakeBear yes, it should works. I use scheduler free non-commercial license for my projects.

**Comment by drakeBear** [comment]
Another Thank You.

**Comment by vadym-vorobel** [comment]
@drakeBear you're welcome
