### ISSUE TITLE
droppable external events do not register at all

### ISSUE THREAD

**Issue by dchan14** [alonoslav/fullcalendar-react#5]
the option for drop does not work in this component.
i am able to get fullcalendars drop to work but not using this component.

is there an option i am missing?

**Comment by vadym-vorobel** [comment]
@dchan14 can you give me an example of how it should work?

**Comment by dchan14** [comment]
http://codepen.io/kotazi/pen/KVoXob
Yea not sure if its the newest fullcalendar issue or what but i downgraded to fullcalendar 2.6 and i am able to just use jquery version in my app

Dc

**Comment by vadym-vorobel** [comment]
@dchan14 Ah, I think, the problem is that my package doesn't have `$.draggable`. I'll add it asap.
Is this the source of your problem?
