### ISSUE TITLE
how to install from npm? 

### ISSUE THREAD

**Issue by juanpgaviria** [alonoslav/fullcalendar-react#6]
Cant find this on npm, could you please help me?

**Comment by vadym-vorobel** [comment]
@juanpgaviria this package is only for MeteorJS now. You can't find it on npm

**Comment by mikelambert** [comment]
Can you please include a comment about this in the README? I just wasted time running into the same problem, trying to install from `github:`, etc.

**Comment by vadym-vorobel** [comment]
@mikelambert sure, thanks
