### ISSUE TITLE
fullCalendar  id or class assignment 

### ISSUE THREAD

**Issue by DeanKamali** [alonoslav/fullcalendar-react#7]
Hi 

How can I target fullCalendar object after it gets rendered 

`<FullCalendar options={calendarOptions} />
`

Say for example, I have a date picker that interacts with fullCalendar, as the component doesn't have id or class prop, I'm unable to go to an arbitrary date, for example 
```
$('#calendar').fullCalendar('gotoDate', '2020-04-24')

```

Any ideas?

**Comment by vadym-vorobel** [comment]
@DeanKamali `calendarOptions` has `id` key. You can try to use it or use state variable instead of `defaultDate` key, like:

```js
const calendarOptions = {
  ...
  defaultDate: this.state.calendarDate,
  ...
};
```

**Comment by DeanKamali** [comment]
Thank you @vadym-vorobel , My question is not about defaultDate which as you know will only be used when the calendar first renders. 

I'm trying to change the date value after calendar renders. 

Can you give me an example of `id` key? I tried using `id: calendar` and tried 

`$('#calendar').fullCalendar('gotoDate', '2020-04-24')`

But no luck, any other ideas?

**Comment by vadym-vorobel** [comment]
@DeanKamali I've tried to use the `id` key and you're right, it doesn't work. But I've successfully tested the dynamic default date (see [this example](https://github.com/vadym-vorobel/fullcalendar-react/tree/master/examples/dynamic-view-date)). Maybe, it will be better to use the React approach, not jQuery. Will it be good for you?
