### ISSUE TITLE
Select an event

### ISSUE THREAD

**Issue by tara-wilson** [alonoslav/fullcalendar-react#9]
Can I use custom views for the events in the calendar? Is there an 'on click' function for the events?

**Comment by vadym-vorobel** [comment]
Hi @tara-wilson !
Yes, you can use [eventClick](https://fullcalendar.io/docs/mouse/eventClick/) callback for your events. Just pass it into fullcalendar settings.

Also, you are able to use all options, include custom views, with this package. Here you can see the list of supported [callbacks](https://github.com/vadym-vorobel/fullcalendar-react/blob/master/lib/utils.js#L1)  and [methods](https://github.com/vadym-vorobel/fullcalendar-react/blob/master/lib/utils.js#L35).

Please, give me feedback about custom views work with my package. I didn't test this case yet.

**Comment by tara-wilson** [comment]
thanks for the quick reply @vadym-vorobel! I'll report back on the custom views soon.
